### ISSUE TITLE
Install fails on Mac OS 10.9.1

### ISSUE THREAD

**Issue by ChuckJonas** [atom/node-keytar#31]
Trying to install keytar and getting a failure.
node: v0.11.9
npm: v3.3.3

Output:
```
$ npm install keytar

> keytar@3.0.0 install /Users/charles/code/MavensMate/node_modules/keytar
> node-gyp rebuild

  CXX(target) Release/obj.target/keytar/src/main.o
In file included from ../src/main.cc:1:
../../nan/nan.h:168:12: error: no template named 'PersistentBase' in namespace
      'v8'; did you mean simply 'PersistentBase'?
    public v8::PersistentBase<T> {};
           ^~~~~~~~~~~~~~~~~~
           PersistentBase
../../nan/nan.h:167:7: note: 'PersistentBase' declared here
class PersistentBase :
      ^
../../nan/nan.h:168:12: error: circular inheritance between
      'v8::PersistentBase<T>' and 'PersistentBase<T>'
    public v8::PersistentBase<T> {};
           ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
../../nan/nan_new.h:181:20: error: no member named 'UnboundScript' in namespace
      'v8'
struct Factory<v8::UnboundScript> : MaybeFactoryBase<v8::UnboundScript> {
               ~~~~^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:21:25: error: cannot initialize a
      parameter of type 'int' with an rvalue of type 'v8::Isolate *'
  return v8::Array::New(v8::Isolate::GetCurrent());
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:2335:31: note: passing
      argument to parameter 'length' here
  static Local<Array> New(int length = 0);
                              ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:26:52: error: too many arguments to
      function call, expected at most single argument 'length', have 2 arguments
  return v8::Array::New(v8::Isolate::GetCurrent(), length);
         ~~~~~~~~~~~~~~                            ^~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:2335:3: note: 'New'
      declared here
  static Local<Array> New(int length = 0);
  ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:33:54: error: too many arguments to
      function call, expected single argument 'value', have 2 arguments
  return v8::Boolean::New(v8::Isolate::GetCurrent(), value);
         ~~~~~~~~~~~~~~~~                            ^~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:5967:1: note: 'New'
      declared here
Handle<Boolean> Boolean::New(bool value) {
^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:70:48: error: too many arguments to
      function call, expected single argument 'time', have 2 arguments
      v8::Date::New(v8::Isolate::GetCurrent(), value).As<v8::Date>());
      ~~~~~~~~~~~~~                            ^~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:2866:3: note: 'New'
      declared here
  static Local<Value> New(double time);
  ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:70:66: error: expected '(' for
      function-style cast or type construction
      v8::Date::New(v8::Isolate::GetCurrent(), value).As<v8::Date>());
                                                         ~~~~~~~~^
../../nan/nan_implementation_12_inl.h:70:68: error: expected expression
      v8::Date::New(v8::Isolate::GetCurrent(), value).As<v8::Date>());
                                                                   ^
../../nan/nan_implementation_12_inl.h:78:55: error: too many arguments to
      function call, expected single argument 'value', have 2 arguments
  return v8::External::New(v8::Isolate::GetCurrent(), value);
         ~~~~~~~~~~~~~~~~~                            ^~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3045:3: note: 'New'
      declared here
  static Local<External> New(void* value);
  ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:88:39: error: no matching function for
      call to 'New'
  v8::Local<v8::ObjectTemplate> tpl = v8::ObjectTemplate::New(isolate);
                                      ^~~~~~~~~~~~~~~~~~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3574:32: note: candidate
      function not viable: no known conversion from 'v8::Isolate *' to
      'Handle<v8::FunctionTemplate>' for 1st argument
  static Local<ObjectTemplate> New(Handle<FunctionTemplate> constructor);
                               ^
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3433:32: note: candidate
      function not viable: requires 0 arguments, but 1 was provided
  static Local<ObjectTemplate> New();
                               ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:94:34: error: too many arguments to
      function call, expected single argument 'value', have 2 arguments
    , v8::External::New(isolate, reinterpret_cast<void *>(callback)));
      ~~~~~~~~~~~~~~~~~          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3045:3: note: 'New'
      declared here
  static Local<External> New(void* value);
  ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:116:41: error: no matching function for
      call to 'New'
    v8::Local<v8::ObjectTemplate> tpl = v8::ObjectTemplate::New(isolate);
                                        ^~~~~~~~~~~~~~~~~~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3574:32: note: candidate
      function not viable: no known conversion from 'v8::Isolate *' to
      'Handle<v8::FunctionTemplate>' for 1st argument
  static Local<ObjectTemplate> New(Handle<FunctionTemplate> constructor);
                               ^
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3433:32: note: candidate
      function not viable: requires 0 arguments, but 1 was provided
  static Local<ObjectTemplate> New();
                               ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:122:36: error: too many arguments to
      function call, expected single argument 'value', have 2 arguments
      , v8::External::New(isolate, reinterpret_cast<void *>(callback)));
        ~~~~~~~~~~~~~~~~~          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3045:3: note: 'New'
      declared here
  static Local<External> New(void* value);
  ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:129:52: error: cannot initialize a
      parameter of type 'FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
      'v8::Isolate *'
    return scope.Escape(v8::FunctionTemplate::New( isolate
                                                   ^~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3347:24: note: passing
      argument to parameter 'callback' here
      FunctionCallback callback = 0,
                       ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:134:38: error: cannot initialize a
      parameter of type 'FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
      'v8::Isolate *'
    return v8::FunctionTemplate::New(isolate, 0, data, signature);
                                     ^~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3347:24: note: passing
      argument to parameter 'callback' here
      FunctionCallback callback = 0,
                       ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:150:33: error: too many arguments to
      function call, expected single argument 'value', have 2 arguments
                              , value).As<v8::NumberObject>();
                                ^~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:2904:3: note: 'New'
      declared here
  static Local<Value> New(double value);
  ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:150:59: error: expected '(' for
      function-style cast or type construction
                              , value).As<v8::NumberObject>();
                                          ~~~~~~~~~~~~~~~~^
../../nan/nan_implementation_12_inl.h:150:61: error: expected expression
                              , value).As<v8::NumberObject>();
                                                            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/keytar/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:101:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:827:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/charles/code/MavensMate/node_modules/keytar
gyp ERR! node -v v0.11.9
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
mavensmate@0.0.39-beta3 /Users/charles/code/MavensMate
├─┬ autocmdr@0.0.7
│ └─┬ winston@0.7.3
│   └── async@0.2.10 
├─┬ jsforce@1.4.1 (git://github.com/joeferraro/jsforce.git#03636ea1ebb780dd8807d0e0602efc3f031b91d5)
│ └─┬ request@2.63.0
│   └─┬ bl@1.0.0
│     └── readable-stream@2.0.2 
├─┬ mocha@2.3.2
│ └─┬ jade@1.11.0
│   └─┬ uglify-js@2.4.24
│     ├── async@0.2.10 
│     └─┬ yargs@3.5.4
│       └── wordwrap@0.0.2 
├─┬ nconf@0.6.9
│ └─┬ optimist@0.6.0
│   └── minimist@0.0.10 
├─┬ season@4.0.3
│ └─┬ fs-plus@2.8.1
│   └── async@0.2.10 
└─┬ swig@1.4.2 (git://github.com/joeferraro/swig.git#397ba138f05f04484abcb1321db0f7f60d843f00)
  ├─┬ optimist@0.6.1
  │ └── minimist@0.0.10 
  └─┬ uglify-js@2.4.24
    ├── async@0.2.10 
    └─┬ yargs@3.5.4
      └── wordwrap@0.0.2 

npm WARN EPACKAGEJSON mavensmate@0.0.39-beta3 license should be a valid SPDX license expression
npm ERR! Darwin 13.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "keytar"
npm ERR! node v0.11.9
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by lucidNTR** [comment]
this should be fixed using dev tools version 7 instead of 6.

**Comment by lucidNTR** [comment]
same applies to recent version 3.0.0 of keytar. build fails if xcode < 7

**Comment by lucidNTR** [comment]
please dont close issue without updating the readme

**Comment by ChuckJonas** [comment]
I updated my xcode (and command) to 7.0.1.  Still getting an error:
```
➜  ~  gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
➜  ~  npm install keytar -g

> keytar@3.0.0 install /usr/local/lib/node_modules/keytar
> node-gyp rebuild

  CXX(target) Release/obj.target/keytar/src/main.o
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:168:12: error: no template named 'PersistentBase' in
      namespace 'v8'; did you mean simply 'PersistentBase'?
    public v8::PersistentBase<T> {};
           ^~~~~~~~~~~~~~~~~~
           PersistentBase
../node_modules/nan/nan.h:167:7: note: 'PersistentBase' declared here
class PersistentBase :
      ^
../node_modules/nan/nan.h:168:12: error: circular inheritance between
      'v8::PersistentBase<T>' and 'PersistentBase<T>'
    public v8::PersistentBase<T> {};
           ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
../node_modules/nan/nan_new.h:181:20: error: no member named 'UnboundScript' in
      namespace 'v8'
struct Factory<v8::UnboundScript> : MaybeFactoryBase<v8::UnboundScript> {
               ~~~~^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:21:25: error: cannot initialize
      a parameter of type 'int' with an rvalue of type 'v8::Isolate *'
  return v8::Array::New(v8::Isolate::GetCurrent());
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:2335:31: note: passing
      argument to parameter 'length' here
  static Local<Array> New(int length = 0);
                              ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:26:52: error: too many arguments
      to function call, expected at most single argument 'length', have 2
      arguments
  return v8::Array::New(v8::Isolate::GetCurrent(), length);
         ~~~~~~~~~~~~~~                            ^~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:2335:3: note: 'New'
      declared here
  static Local<Array> New(int length = 0);
  ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:33:54: error: too many arguments
      to function call, expected single argument 'value', have 2 arguments
  return v8::Boolean::New(v8::Isolate::GetCurrent(), value);
         ~~~~~~~~~~~~~~~~                            ^~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:5967:1: note: 'New'
      declared here
Handle<Boolean> Boolean::New(bool value) {
^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:70:48: error: too many arguments
      to function call, expected single argument 'time', have 2 arguments
      v8::Date::New(v8::Isolate::GetCurrent(), value).As<v8::Date>());
      ~~~~~~~~~~~~~                            ^~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:2866:3: note: 'New'
      declared here
  static Local<Value> New(double time);
  ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:70:66: error: expected '(' for
      function-style cast or type construction
      v8::Date::New(v8::Isolate::GetCurrent(), value).As<v8::Date>());
                                                         ~~~~~~~~^
../node_modules/nan/nan_implementation_12_inl.h:70:68: error: expected
      expression
      v8::Date::New(v8::Isolate::GetCurrent(), value).As<v8::Date>());
                                                                   ^
../node_modules/nan/nan_implementation_12_inl.h:78:55: error: too many arguments
      to function call, expected single argument 'value', have 2 arguments
  return v8::External::New(v8::Isolate::GetCurrent(), value);
         ~~~~~~~~~~~~~~~~~                            ^~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3045:3: note: 'New'
      declared here
  static Local<External> New(void* value);
  ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:88:39: error: no matching
      function for call to 'New'
  v8::Local<v8::ObjectTemplate> tpl = v8::ObjectTemplate::New(isolate);
                                      ^~~~~~~~~~~~~~~~~~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3574:32: note: candidate
      function not viable: no known conversion from 'v8::Isolate *' to
      'Handle<v8::FunctionTemplate>' for 1st argument
  static Local<ObjectTemplate> New(Handle<FunctionTemplate> constructor);
                               ^
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3433:32: note: candidate
      function not viable: requires 0 arguments, but 1 was provided
  static Local<ObjectTemplate> New();
                               ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:94:34: error: too many arguments
      to function call, expected single argument 'value', have 2 arguments
    , v8::External::New(isolate, reinterpret_cast<void *>(callback)));
      ~~~~~~~~~~~~~~~~~          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3045:3: note: 'New'
      declared here
  static Local<External> New(void* value);
  ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:116:41: error: no matching
      function for call to 'New'
    v8::Local<v8::ObjectTemplate> tpl = v8::ObjectTemplate::New(isolate);
                                        ^~~~~~~~~~~~~~~~~~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3574:32: note: candidate
      function not viable: no known conversion from 'v8::Isolate *' to
      'Handle<v8::FunctionTemplate>' for 1st argument
  static Local<ObjectTemplate> New(Handle<FunctionTemplate> constructor);
                               ^
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3433:32: note: candidate
      function not viable: requires 0 arguments, but 1 was provided
  static Local<ObjectTemplate> New();
                               ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:122:36: error: too many
      arguments to function call, expected single argument 'value', have 2
      arguments
      , v8::External::New(isolate, reinterpret_cast<void *>(callback)));
        ~~~~~~~~~~~~~~~~~          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3045:3: note: 'New'
      declared here
  static Local<External> New(void* value);
  ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:129:52: error: cannot initialize
      a parameter of type 'FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
      'v8::Isolate *'
    return scope.Escape(v8::FunctionTemplate::New( isolate
                                                   ^~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3347:24: note: passing
      argument to parameter 'callback' here
      FunctionCallback callback = 0,
                       ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:134:38: error: cannot initialize
      a parameter of type 'FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
      'v8::Isolate *'
    return v8::FunctionTemplate::New(isolate, 0, data, signature);
                                     ^~~~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:3347:24: note: passing
      argument to parameter 'callback' here
      FunctionCallback callback = 0,
                       ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:150:33: error: too many
      arguments to function call, expected single argument 'value', have 2
      arguments
                              , value).As<v8::NumberObject>();
                                ^~~~~
/Users/charles/.node-gyp/0.11.9/deps/v8/include/v8.h:2904:3: note: 'New'
      declared here
  static Local<Value> New(double value);
  ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:150:59: error: expected '(' for
      function-style cast or type construction
                              , value).As<v8::NumberObject>();
                                          ~~~~~~~~~~~~~~~~^
../node_modules/nan/nan_implementation_12_inl.h:150:61: error: expected
      expression
                              , value).As<v8::NumberObject>();
                                                            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/keytar/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:101:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:827:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/keytar
gyp ERR! node -v v0.11.9
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "keytar" "-g"
npm ERR! node v0.11.9
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/charles/npm-debug.log

**Comment by lucidNTR** [comment]
sorry my mistake, its a sepereate issue from the one i was talking about. can you try updating node js to the latet 4.x ? only idea i have right now...

**Comment by ChuckJonas** [comment]
Awesome, that seems to have resolved it.  Thanks!

**Comment by lucidNTR** [comment]
cool --> update readme to show minimal node version.
